// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "tokenize/domain"

	mock "github.com/stretchr/testify/mock"
)

// TradingRepository is an autogenerated mock type for the TradingRepository type
type TradingRepository struct {
	mock.Mock
}

// GetDepth provides a mock function with given fields: ctx, symbol
func (_m *TradingRepository) GetDepth(ctx context.Context, symbol string) (*domain.TradDepth, error) {
	ret := _m.Called(ctx, symbol)

	var r0 *domain.TradDepth
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.TradDepth); ok {
		r0 = rf(ctx, symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TradDepth)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTradingRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewTradingRepository creates a new instance of TradingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTradingRepository(t mockConstructorTestingTNewTradingRepository) *TradingRepository {
	mock := &TradingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
